name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Print current date
        run: |
          date
      - name: Print current directory content in long format
        run: |
          ls -l
      - name: Say hello
        run: |
          echo "Hello World!"